#+title: Food Trucks
#+author: John Shaughnessy

* New things are easy to misunderstand

- They are easy to miss.
- New things might *look* like other things.
- New things might *sound* like other things.
- New things might *seem* like other things.

* Hubs is a new thing

And it's easy to misunderstand.

If I describe its gameplay, you might think it's another "metaverse game" like
- Roblox,
- Rec Room,
- Meta,
- VR Chat.

If I describe its extensibility, you might think it's another game engine like
- Unreal,
- Unity,
- Godot

If I describe its philosophy, you might think it's another
- mastodon / activity pub.
- element / matrix protocol,

No matter where I start, explaining Hubs "directly" is difficult.

So, allow me to take an indirect path.

* Let's forget about Hubs

Let's forget about Hubs for a moment.

Let's forget about
- the metaverse,
- games,
- the immersive web,
- standards,
- artist tools,
- communities,
- tech companies,
- governance, and
- the powerful forces that influence our societies, economies, cultures, and lives.

Let's forget all that.

* Let's talk about food trucks.

Here is a long list of things I want to say about food trucks.

** I love food trucks.

I love eating the food sold by food trucks.

I love discovering new food trucks.

I love the /concept/ of food trucks.

** Food trucks are visually unique

Every food truck has its own paint job.

** Food trucks have unique menus.

Every food truck has its own recipes.

** Food trucks have equipment.

They've got friers and burners and freezers and blenders.

** Food trucks need ingredients.

Bring your own tomatoes - they don't come with the truck.

** Food trucks serve food to patrons.

People eat at food trucks because they love the food, not because they want their own food truck.

** Food trucks are mobile.

They go all over the place.

They go where the people who drive them /want them/ to go.

They go where there are people who love the food.

** Food trucks are small.

Each one is built so that a small number of people can operate one.

** Food trucks are not good at everything.

They are less convenient than home kitchens.

They have less space than restaurant kitchens.

They have only the essential tools for making the menu they sell.

They do not offer substitutions.

They have a small menu.

** Food trucks are designed for their operators.

The capabilities, layout, and organization of the food truck is designed primarily with the operator in mind.

They rarely features that directly benefit patrons of the food truck.

** Food trucks are customized by their operators.

Burger trucks have grills.

Fried chicken trucks have friers.

Smoothie trucks have blenders.

** Food trucks power small businesses.

It's /hard/ to start a business.

It's /expensive/ and /risky/ to start a business.

Food trucks are less expensive than owning a restaurant.

Successful food trucks sometimes graduate into restaurants. Others franchise and expand.

* Hubs are like food trucks

Here is a long list of things I want to say about hubs.

** I love hubs.

I love spending time with people in hubs.

I love discovering new hubs.

I love the /concept/ of hubs.

** Hubs are visually unique.

Every hub has its own UI, color scheme, home screen, and pages.

** Hubs host unique experiences.

Every hub has its own avatars, environments, events, and gameplay.

** Hubs have built-in capabilities.

Hubs have 3D graphics, voice chat, video chat, file storage, and account management.

** Hubs need content.

Bring your own avatars, scenes, and the people you want to play with.

** Hubs entertain and help their visitors.

People visit hubs because they love the experience, not because they want their own hub.

** Hubs are websites.

They're accessible everywhere.

They run on mobile devices, tablets, laptops, gaming computers, and VR/AR headsets.

They're built for the people who love to visit them. Not just for people with high-end computers or game consoles.

** Hubs are small.

Each one is built so that a small number of people can operate one

** Hubs are not good at everything.

They are less convenient than a video call.

They are less extensible than a general purpose game engine.

They have only the essential tools for having a multiplayer experience.

They have preset environments.

They are built to enable specific experiences.

** Hubs are designed for their operators.

The admin panel, permissions, capabilities, layout, and organization of the hub is designed primarily with the operator in mind.

** Hubs power small creative businesses.

It's /hard/ to start a creative business.

It's /expensive/ and /risky/ to start a creative business.

Building with Hubs is less expensive than building with other game engines.

We expect successful Hubs to sometimes graduate into a unique immersive application or service. Others will replicate their Hub with variations and expand with servers in new regions.

* Why Hubs is a new thing

Now we can see why.

** Hubs aren't like other "metaverse games"

Consider Roblox, Rec Room, Meta, and VR Chat. These are not food trucks.

They're all... RESTAURANTS!

But imagine how bad it feels to be a chef at such a restaurant...

As a chef, you don't work for the restaurant.

You're just a patron who likes cooking.

The restaurant supplies a limited set of ingredients.

You must not stray too far from the pre-approved menu.

If the restaurant dislikes you or your food, they'll kick you out.

If the restaurant loves your food, they will sell it for a profit. If you're lucky, they might let you have some of that money. But more than likely all you'll earn is some monopoly money.

You can't take your recipes with you to start your own restaurant. Those recipes -- all your hard work -- all the meals you've prepared and served... Those are the property of the restaurant.

The restaurant boasts an impressively large menu of user-generated content. The snowball starts to roll. Soon enough everyone is eating most of their meals at this restaurant.

I don't mean to suggest that the restaurant does not deserve some compensation for their work. After all, they provide valuable services and equipment. They maintained the kitchen and cleaned the tables and welcomed the guests and payed the property taxes. That effort is certainly worth rewarding.

The problem, though, is that when one of these restaurants gets popular, they franchise all over the world, and the balance of power is extremely in the restaurant's favor. Individual chefs, who provided the creative spark, who brought their friends to the restaurant, who put up with the day the friers broke and the blender exploded... Those chefs are left out in the cold, burning their monopoly money for warmth.

** The Hubs engine is not another general purpose game engine

Consider Unreal Engine and Godot. These are not food trucks.

They're much more versatile than that. And consequently, much more complicated.

You can build practically anything with them: buildings, vehicles, bridges, space elevators. There is nothing particularly food-trucky about them.

But let's imagine that we want a food truck, and we choose one of these engines as our starting point.

*** *Unreal engine* is a world-class commercial kitchen.

It's got 11 sinks, 400 pots & pans of all shapes and sizes, ceiling-mounted vents, 6 dish washers, and state-of-the-art high-precision induction burners for heating salmon to exactly 122°F before a flash-in-the-pan sear.

It takes a team of 40 experienced chefs to operate effectively and really shines when the team grows beyond 100 people.

Unreal engine is /extremely good/ for what it's good at: Allowing a team of trained professionals create one-of-a-kind, AAA dining experiences.

But it is exactly the wrong tool for a pair of chefs who are excited to share their favorite spicy fried chicken recipe.

*** *Godot* is like a build-your-own-auto manufacturer.

Godot is much more approachable than Unreal Engine. It also feels more light weight and mobile. The batteries are included, and they've designed the application from the ground-up to be easier to learn for artists, level designers, animators, and everyone in between.

With Godot, you can make all sorts of vehicles. You can make a racecar, a school bus, a tank, a plane, a submarine, a motorcycle, a bicycle.

You can choose the wheels you want. And the engine. And the body. And whether it has jet packs. And whether it's actually a talking cat-bus a la My Neighbor Totoro. https://en.wikipedia.org/wiki/Catbus

In theory, you could build a food truck with Godot. But if what you wanted spend your time doing was perfecting your fish taco recipe, Godot is not the right tool for you.

** Hubs is mission-driven

Consider Mastodon or the Matrix.org Foundation. These mission-driven organizations each have a vision for decentralized, secure, private, unencumbered and global communication.

Matrix.org and Mastodon have different approaches to decentralization and product development.

Chat clients like Element communicate via the Matrix protocol.
Mastodon servers communicate via the Activity pub protocol.

The goals of each are noble and their strategies for achieving them are viable. I hope they succeed.

At risk of stretching the analogy too thin, let's keep talking about food trucks.

*** Food trucks need parking and business permits.

Food trucks aren't allowed to park just anywhere. Local laws still apply.

It's important that a society create fair and transparent rules about who is allowed to do what.

A food truck is not allowed to park in front of a fire hydrant no matter how delicious the noodles it serves is. It puts everyone else at unacceptable risk -- especially if the noodles are spicy enough to be deemed a fire hazard!

*** Food trucks must meet food safety standards.

Food truck operators must not serve food that has been poisoned, contaminated, and spoiled. Beyond the reputational harm they'd do to themselves and the gastrointestinal harm they'd do to their patrons, they might also be held legally responsible if found negligent.

*** Food trucks have political consequences

Like any business, food trucks are subject to regulations, taxes, and inspections decided by political processes of the jurisdictions where they operate.

Those political processes invite fundamental issues of ethics, morality, access, representation, and governance. Food truck operators, their patrons, and the communities that host them all influence those political processes.

*** Let's get back to Hubs, Mastodon, and Matrix.

Hubs has not published or implemented a particular protocol. While there is demand for an identity and asset management service that lives outside of each hub instance, we have not built such a product, service, or protocol.

Hubs today is an enabling technology. It is a seed we plant with the dream of a beautiful future. We will not achieve a beautiful future alone.

With Hubs, "we aim to create the most joyful online social experiences by bringing the best of real world interactions to the open web".

If we succeed, then many chefs will operate many food trucks. We will have avoided a future where chefs are exploited or patrons aren't free to support the chefs they like most. We will have empowered creators and rewarded those who have added value (rather than extracting that value for ourselves alone).

*** Making money is not the end goal.

Consider Mozilla's mission:

> Our mission is to ensure the Internet is a global public resource, open and accessible to all. An Internet that truly puts people first, where individuals can shape their own experience and are empowered, safe and independent.

Whatever you want to call it -- the "metaverse", the immersive web, or just "video games" -- people are increasingly gathering in multiplayer experiences to create, connect, play, learn and express themselves.

These applications have /massive/ political consequences. These applications know who you spend time with, what you talk about, where you look, for how long, and whether your pupils dilated ever so slightly. They have unprecedented access to YOU. It doesn't have to be this way. I want to live in a future where I can experience the immersive web and feel confident I'm not being recorded, tracked, manipulated, and exploited by unseen actors.

Notice that there are hardly any "food safety standards" for these applications.

We believe that with Hubs, we have an opportunity to avoid this family of applications from falling into the same centralized, exploitative, and dangerous patterns of social media companies today.

*** We still want to make money

We still hope to create a sustainable business around Hubs.

The business model of social media companies has been to harvest, analyze, exploit, and sell user data. This creates an asynchronous power dynamic between platforms and a platforms users.

By creating valuable products people pay for, we sustain the mission and maintain a direct relationship with the people we serve. (With Hubs, you are /not/ the product.)

* What people pay us for
Surely there's nothing more to say about food trucks

Oh but of course there is.

In the previous section, I talked about making money. This is how we do that, and why everyone gets to feel good about how we're doing it.

Hubs (aka "hub instances") come in a variety of flavors.

** Hubs Cloud

Hubs Cloud is our "self-hosted" option. You pay a convenience fee to Mozilla and hosting fees to the cloud provider of your choice to own and operate your own Hub. This is like buying your own food truck.

There are some advantages to having your own hub /completely/. It gives you ultimate flexibility and control. You can run it side-by-side with other cloud services you own and operate. It is absolutely the best choice for some customers.

Most people don't want or need this level of control. It is akin for being responsible for all the maintenance of the food truck. Burner broke? You fix it. Flat tire? Deal with it yourself. You want a new freezer to store berries and icecream? Install it yourself.

Cost is also a considerable downside. Reserving dedicated services from cloud providers does not need to be prohibitively expensive, but most people still prefer a less expensive option, even if it means sharing servers. Most of all, many people prefer predictable pricing. They don't want to calculate and project and analyze their bills every month.

** Managed Hubs

Recently, we launched an "early access" program for Hubs.

Effectively, it lets people rent a food truck. We fix the tires. We upgrade the fridge. We keep your servers humming happily so that you can think about fish tacos and building escape-the-room games.

This is a product I have dreamt about for a long time:

I visit a website, pay some monthly fee, get my own multiplayer game (that I can completely customize, from the color scheme to the content to the code), run it on my own website, where I can commercialize it directly to end users.

This to me is mind blowing. And I hope it's as exciting to creative people around the world as it is to me. There are plenty of rough edges we need to iron out, but the essential pieces are all there.

* Where to focus

** Where a food truck company focuses

As a company that designs, manufactures, maintains, sells and rents out food trucks, we are part of something much bigger than ourselves.

A food truck company doesn't invent recipes.

It doesn't procure ingredients.

It doesn't create point-of-sale systems.

It doesn't create apps, ads, or promotions for particular truck owners.

It doesn't try to make the best falafel.

It doesn't create cooking tutorials or offer cooking classes.

It doesn't write the laws of the road, decide where to park, or determine what permits food truck operators need.

Its role is to provide high-quality, fit-to-purpose vehicles that meet the needs of their customers, the chefs.

A food truck company needs an ecosystem in which it can embed itself.

It needs chefs who want autonomy and flexibility.

It needs patrons who enjoy trying new cuisines from non-traditional restaurants.

It needs a society whose laws ensure that chefs can run businesses and patrons can eat safely.

It needs expertise in auto manufacturing, interior design, and yes -- even cooking, though their best feedback will be from their chefs.

** Where we must focus

We have and hear so many exciting ideas about Hubs.

It's difficult to know what to focus on.

Most of us are not just in love with food trucks.
- We're in love with food.
- We're in love with cooking and with eating.
- We love the people who eat.
- We love the people who cook.
- We care about the laws and the rules and the norms and the culture surrounding food trucks.
- We love to dream about the future of food trucks. The future of vehicles. And the future of food.

For the ecosystem to succeed, we must provide reliable, high-quality, well-designed, well-maintained food trucks.

If we can do /more/ than that, that's great. But we aren't doing that basic piece well yet.

If we try to build food trucks /and also do other things/, then we are splitting focus, and we'll get less far.

Taking this route is a calculated risk. By focusing on building the best food trucks we can, we assume:
- Chefs will bring their expertise to craft wonderful menu items.
- Point-of-sale systems will be created to facilitate and ease transactions.
- Farmers and wholesalers will provide ingredients to chefs.
- Politicians and community representatives will discuss regulations and safety.
- Customers will eat food.
- We'll dream about the future together.

Of course, there may be things outside of our core focus to stimulate the ecosystem, jump-start a virtuous cycle, or engage a flywheel effect.

But we should be wary not to confuse our role with someone else's, or split our efforts too widely. Just as the entire ecosystem cannot thrive without skilled chefs, neither can it thrive without well-built food trucks.

As food truck manufacturers, we will have a seat at the table - but not authoritative control - over the standards and laws that govern the next wave of interactive computing. This is as it should be. These standards and laws will effect all of us. All of us together should write them.

* Appendix

There are some corrections to make.

** Hubs are also designed for their visitors

Above, I claimed that Hubs are designed primarily for their operators.

That's only partially true.

Unlike food trucks whose patrons already know how to eat, visitors to a Hub /do not/ already know how to navigate them.

The way we overcome this challenge is by teaching people how to navigate and also copying common design patterns in 3D games that visitors are likely to have encountered from their other experiences.

Ideally, hubs appeal to an even wider audience than games historically have. There's reason to believe this is true: The raw capabilities are a superset of games, video calls, and most social media apps.

This means we should expect to spend unusually high effort on teaching and offering simpler alternatives to navigation than most games need to.

In many ways, I expect hubs to appeal to people who /don't/ particularly like games. People who like games have thousands of distinct experiences to choose from. Multiplayer, single player, competitive, casual. For people who like connecting with others, expressing themselves, and building things to share -- Hubs offers new ways of doing that.

** Hubs do need to provide some ingredients

Above, I mentioned that food trucks don't provide ingredients and hub instances don't provide content like avatars and environments. This is not quite true. We believe that people need high-quality default content. We also think that content should stay fresh, and it should be easy to find more of what you're looking for and enjoy.

I think we are in an uncomfortable middle ground right now with content. It seems like it's not /quite/ right that it always lives within a Hub instance. And it's not /quite/ right that we provide it. Sketchfab seemed like a critical part of the overall vision for an immersive web that rewards creators. Now that Sketchfab is owned by Epic Games, I'm not so sure anymore.
